jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man
    on_success:
      - script: echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - script: echo 'this is on_failure step of dv-man of type manifest'
    flags:
      - dv

  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionName: latest
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man

  - name: dv-man-versionNumber
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionNumber: 1
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man

  - name: box-man
    type: manifest
    steps:
      - IN: box-image
        pull: false
      - IN: box-opts
      - IN: box-params
      - TASK: managed
    flags:
      - box

  - name: multi-manifest
    type:  deploy
    steps:
      - IN: box-man
      - IN: dv-man
      - IN: env-test
      - TASK: managed
        deployMethod: upgrade

  - name: release-one
    type: release
    steps:
      - IN: version-resource
      - IN: dv-man
      - TASK: managed
        bump: major

  - name: infra-provision
    type: runSh
    steps:
      - IN: infra-repo
      - TASK:
        - script: ls
        - script: ./IN/infra-repo/gitRepo/provision.sh
    on_success:
      - script: echo 'This block executes after TASK section executes successfully'
      - NOTIFY: slackNotifcation

  - name: build-dv-image
    type: runSh
    steps:
      - IN: infra-repo
      - TASK:
        - script: "echo 'versionName=latest' > /build/state/dv-image.env"
      - OUT: dv-image

  - name: app-rawFile-manifest
    type: manifest
    steps:
      - IN: app-package-rawFile
      - IN: trigger-rawFile-manifest


  # Fetches file from URL and transfer to the nodes in the cluster
  # and executes the commands and scripts on the nodes
  - name: app-rawFile-deploy
    type: deploy
    steps:
      - IN: app-rawFile-manifest
        force: true
      - TASK:
          - script: cd /tmp/shippable && ls
          - script: ~/restartWebServerService.sh
